Feature/add users admin panel
VVOvsyannikov/TaskManager pull request #11
Opened 2022-10-04 21:24 UTC by VVOvsyannikov

2022-10-05 06:56 UTC, greybutton requested changes

2022-10-05 06:56 UTC, greybutton commented on app/models/task.rb
> +  StateMachines::Machine.ignore_method_conflicts = true
это зачем?

2022-10-05 06:56 UTC, greybutton commented on app/views/admin/users/_form.html.slim
> +- if local_assigns[:new]
форму можно проще сделать, без ифа, другую переменную передать

2022-10-05 19:34 UTC, VVOvsyannikov commented
> это зачем?

Без него вываливается ошибка.
На сколько понял из Stackoverflow - это проблема в StateMachine
![Screenshot from 2022-10-05 22-29-29](https://user-images.githubusercontent.com/93976951/194146257-b8201c77-1f57-4eb9-8a25-e9c854b28087.png)

2022-10-05 19:34 UTC, VVOvsyannikov commented on app/views/admin/users/_form.html.slim
> +- if local_assigns[:new]
> форму можно проще сделать, без ифа, другую переменную передать

да, после дня ног в тренажерке мозги не работают)

2022-10-06 06:10 UTC, greybutton requested changes

2022-10-06 06:10 UTC, greybutton commented on app/views/admin/users/edit.html.slim
> +  = render 'form', url: admin_user_path(@user)
получилась форма в форме, это не верно

2022-10-06 06:13 UTC, greybutton commented
насчет ошибки стейт машины, у других студентов ее нет, либо они про нее не пишут)
1 нужно точно узнать в каком тесте выпадает такая ошибка
2 может быть убрать sequence :state и ошибка уйдет

2022-10-06 20:15 UTC, VVOvsyannikov commented
Разобрался с rails-slim, оказалось, что он чувствителен к отступам. Поэтому не мог убрать дублирование форм.
Разобрался с автоматом, у меня был эвент :test, что и вызывало ошибку "Instance method "test" is already defined in Object". Переименовал.

2022-10-07 08:03 UTC, greybutton approved these changes

2022-10-10 06:42 UTC, merged