feature/add-API, fix tasks test
VVOvsyannikov/TaskManager pull request #12
Opened 2022-10-06 21:26 UTC by VVOvsyannikov

2022-10-07 08:05 UTC, greybutton requested changes

2022-10-07 08:05 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +# require 'task_serializer'
это зачем?

2022-10-07 08:05 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +  respond_to :json, :html
почему html? жсон можно убрать на уровень апи

2022-10-07 08:05 UTC, greybutton commented on test/factories/sequence.rb
> +  # sequence :state, [:new_task, :archived, :in_development, :in_qa, :in_code_review, :ready_for_release, :released].sample
если не нужно, то удаляем код, а не комментируем его

2022-10-07 08:05 UTC, greybutton commented on test/factories/tasks.rb
> +    expired_at { nil }
почему nil?

2022-10-07 15:46 UTC, greybutton requested changes

2022-10-07 15:46 UTC, greybutton commented on test/factories/tasks.rb
> +    expired_at { }
почему  { }?

2022-10-07 18:12 UTC, VVOvsyannikov commented on test/factories/tasks.rb
> +    expired_at { }
![image](https://user-images.githubusercontent.com/93976951/194622602-7d13a111-8ae1-4419-8020-a3ebf29a2375.png)
тест ожидает nil
что-то с моделью не то?

2022-10-08 09:37 UTC, greybutton approved these changes

2022-10-10 06:41 UTC, merged