Feature/taskmanager tasks
VVOvsyannikov/TaskManager pull request #15
Opened 2022-10-31 22:15 UTC by VVOvsyannikov

2022-11-01 19:53 UTC, greybutton requested changes

2022-11-01 19:53 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      result.includes(:author, :assignee).order(id: :desc).
1 ордер в идеале с фронта передается через рансак и не хардкодится в апи
2 зачем includes(:author, :assignee)?

2022-11-01 19:53 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    end
почему так?

2022-11-01 19:53 UTC, greybutton commented on app/javascript/components/AddPopup/AddPopup.js
> +import TaskForm from '../../forms/TaskForm/TaskForm.js';
from 'forms/TaskForm';

2022-11-01 19:53 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +
1 `from '../../` таких относительных импортов можно избежать 
2 сначала импорты внешних пакетов, потом внутренние файлы

2022-11-01 19:53 UTC, greybutton commented on app/javascript/forms/EditForm/EditForm.js
> +import React from 'react';
этот компонент не в forms должен быть

2022-11-01 19:53 UTC, greybutton commented on app/javascript/components/Task/Task.js
> +import useStyles from './useStyles.js';
from './useStyles';

2022-11-01 19:53 UTC, greybutton commented on app/javascript/components/AddPopup/index.js
> +import AddPopup from './AddPopup.js';
from './AddPopup';

2022-11-01 19:53 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from '../EditPopup';
поправить импорты

2022-11-01 19:53 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      <NewTaskButton onClick={handleOpenAddPopup} />
можно было не выносить в отдельный компонент

2022-11-01 19:53 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +import FetchHelper from '../utils/fetchHelper.js';
1 импорты
2 расширение файла

2022-11-01 19:53 UTC, greybutton commented on config/application.rb
> +    config.web_console.permissions = '172.21.0.1'
зачем?

2022-11-01 19:53 UTC, greybutton commented on config/webpack/loaders/erb.js
> +module.exports = {
зачем?

2022-11-01 19:53 UTC, greybutton commented on db/seeds.rb
> +    Task.create!(name: "Test task #{i}", description: "This is a test task #{i} with state #{state}", author_id: 1, assignee_id: 7, state: state )
что значит 1 и 7?

2022-11-01 19:53 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    params.require(:task).permit(:name, :description, :author_id, :assignee_id, :state_event)
почему изменено?

2022-11-01 21:34 UTC, VVOvsyannikov commented on app/controllers/api/v1/tasks_controller.rb
> +      result.includes(:author, :assignee).order(id: :desc).
1. Но у нас пока не реализована сортировка на фронте. В задачах урока было: "и поправить сортировку на бэкенде, чтобы новые карточки появлялись вверху колонки".
Мне показалось так красивее, чем вот такая штука: RANSACK_DEFAULT_SORT = 'id ASC'
2. Убирал n+1 там куча запросов в базу летело.

2022-11-01 21:37 UTC, VVOvsyannikov commented on app/controllers/api/v1/tasks_controller.rb
> +    end
Мы получаем 2 разных запроса с фронта:
1. в случае перемещения таски между колонок, получаем id таски и название метода транзитера.
Чтобы поменять стейт, нужно выполнить соответствующий метод стейт машины.
2. в случае изменения таски, мы получаем объект таск и тогда его можно просто апдейтить используя стронг парамсы.

2022-11-01 21:53 UTC, VVOvsyannikov commented on config/application.rb
> +    config.web_console.permissions = '172.21.0.1'
Артефакты, с какой-то ошибкой ковырялся. К тому же сломали тесты. Убрал.

2022-11-01 21:57 UTC, VVOvsyannikov commented on config/webpack/loaders/erb.js
> +module.exports = {
я не помню, чтобы я туда лазил. Может какой-то компонент установил...
Вероятно когда я разбирался с Вебпакером.

2022-11-01 22:12 UTC, VVOvsyannikov commented on db/seeds.rb
> +    Task.create!(name: "Test task #{i}", description: "This is a test task #{i} with state #{state}", author_id: 1, assignee_id: 7, state: state )
Это были айдишники пользователей, созданных руками в консоли ранее. Ближайшие не пустые записи.
Переписал по красивее.

2022-11-01 22:12 UTC, VVOvsyannikov commented on app/controllers/api/v1/tasks_controller.rb
> +    params.require(:task).permit(:name, :description, :author_id, :assignee_id, :state_event)
Ошибка. Исправил.

2022-11-01 22:25 UTC, VVOvsyannikov commented on app/javascript/components/AddPopup/AddPopup.js
> +import TaskForm from '../../forms/TaskForm/TaskForm.js';
так всё ломается, не находит модуль

2022-11-01 22:29 UTC, VVOvsyannikov commented on app/javascript/forms/EditForm/EditForm.js
> +import React from 'react';
перенес в EditPopup

2022-11-01 22:31 UTC, VVOvsyannikov commented on app/javascript/repositories/TasksRepository.js
> +import FetchHelper from '../utils/fetchHelper.js';
Убрал расширение. С путями в импортах не разобрался.

2022-11-01 22:35 UTC, VVOvsyannikov commented on app/javascript/components/EditPopup/EditPopup.js
> +
Пересортировал импорты.

2022-11-01 22:35 UTC, VVOvsyannikov commented on app/javascript/components/AddPopup/AddPopup.js
> +import TaskForm from '../../forms/TaskForm/TaskForm.js';
![image](https://user-images.githubusercontent.com/93976951/199354862-6b6e0573-adda-4df4-a3f1-1993ca193c34.png)

2022-11-02 05:17 UTC, greybutton requested changes

2022-11-02 05:17 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    end
эти два варианта не работают с таким кодом?
```
    task = Task.find(params[:id])
    task.update(task_params)
```

2022-11-02 05:17 UTC, greybutton commented on app/javascript/forms/TaskForm/TaskForm.js
> +import { pick, propOr } from 'ramda';
почему TaskForm.js в папке TaskForm?

2022-11-02 05:17 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +import Form from './EditForm/EditForm';
добавь в editform index.js как у остальных компонентов

2022-11-02 05:17 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from '../EditPopup';
1 компоненты нужно импортировать через `from 'components/`
2 добавить порядка, например компоненты друг за другом добавляются

2022-11-02 05:17 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +
убрать относительный импорт

2022-11-02 05:17 UTC, greybutton commented on config/webpack/loaders/erb.js
> +module.exports = {
надо разобраться нужен этот файл или нет, если нет, то удалить

2022-11-02 05:19 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      result.includes(:author, :assignee).order(id: :desc).
1 можешь добавить на фронте. такой хардкод, не красивее
2 как узнал про n+1?

2022-11-02 18:24 UTC, VVOvsyannikov commented on app/controllers/api/v1/tasks_controller.rb
> +    end
Я понял, поправил, завернул объект { stateEvent: transition.event } в { task }.

2022-11-02 18:33 UTC, VVOvsyannikov commented on app/controllers/api/v1/tasks_controller.rb
> +    end
![image](https://user-images.githubusercontent.com/93976951/199573064-548e80a7-1ac8-487c-8070-00b8612eae5e.png)

2022-11-03 20:58 UTC, VVOvsyannikov commented on app/controllers/api/v1/tasks_controller.rb
> +      result.includes(:author, :assignee).order(id: :desc).
1. Сделал переключатель режима сортировки на фронте.
2. Честно, не помню. Я считал, что этот вопрос базовый, все должны знать. Он из серии 100 вопросов на собеседовании.

2022-11-03 20:59 UTC, VVOvsyannikov commented on app/javascript/components/Task/Task.js
> +import useStyles from './useStyles.js';
Исправил

2022-11-03 20:59 UTC, VVOvsyannikov commented on app/javascript/components/AddPopup/index.js
> +import AddPopup from './AddPopup.js';
Исправил

2022-11-03 20:59 UTC, VVOvsyannikov commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from '../EditPopup';
Исправил

2022-11-03 21:08 UTC, VVOvsyannikov commented on app/javascript/forms/TaskForm/TaskForm.js
> +import { pick, propOr } from 'ramda';
Вынес в папку forms

2022-11-03 21:12 UTC, VVOvsyannikov commented on app/javascript/repositories/TasksRepository.js
> +
исправил

2022-11-03 21:12 UTC, VVOvsyannikov commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from '../EditPopup';
исправил

2022-11-03 21:41 UTC, VVOvsyannikov commented on app/javascript/components/EditPopup/EditPopup.js
> +import Form from './EditForm/EditForm';
Добавил

2022-11-03 21:43 UTC, VVOvsyannikov commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      <NewTaskButton onClick={handleOpenAddPopup} />
перенес в TaskBoard

2022-11-03 21:55 UTC, VVOvsyannikov commented on config/webpack/loaders/erb.js
> +module.exports = {
Он от гема rails-erb-loader...
Удалил.

2022-11-06 14:06 UTC, greybutton approved these changes

2022-11-06 14:13 UTC, merged