add NewRelic
VVOvsyannikov/TaskManager pull request #23
Opened 2022-11-22 20:44 UTC by VVOvsyannikov

2022-11-23 05:31 UTC, greybutton requested changes

2022-11-23 05:31 UTC, greybutton commented on newrelic.yml
> +  license_key: eu01xx81e0a7ebc15dca95bc36a2070e1202NRAL
токены не хранят в коде. сгенерируй новый токен и добавь его через переменные окружения (environment variables)

2022-11-23 05:54 UTC, VVOvsyannikov commented on newrelic.yml
> +  license_key: eu01xx81e0a7ebc15dca95bc36a2070e1202NRAL
чорт, те же грабли... не увидел.

2022-11-24 06:32 UTC, greybutton requested changes

2022-11-24 06:32 UTC, greybutton commented on newrelic.yml
> +  license_key: NEW_RELIC_LICENSE_KEY
переменные среды разве так сработают?

2022-11-24 06:32 UTC, greybutton commented on newrelic.yml
> +  # license_key: eu01xx81e0a7ebc15dca95bc36a2070e1202NRAL
если код не нужен, то он удаляется, а не комментируется

2022-11-24 06:40 UTC, VVOvsyannikov commented on newrelic.yml
> +  license_key: NEW_RELIC_LICENSE_KEY
да, 33 раза перепроверил, логи на сервере идут

2022-11-24 06:41 UTC, VVOvsyannikov commented on newrelic.yml
> +  # license_key: eu01xx81e0a7ebc15dca95bc36a2070e1202NRAL
это фиаско... сгораю от стыда

2022-11-25 05:43 UTC, greybutton requested changes
можешь рассказать как роллбар делал?

2022-11-25 05:43 UTC, greybutton commented on newrelic.yml
> +  license_key: NEW_RELIC_LICENSE_KEY
ньюрелик для прода нужен, а не для разработки. Для разработки можно в композ файле любую строку подставить, чтобы не падало, если падает, и убрать .env файл

И не понял, как ты расчитываешь, что такой сетап в проде заработает. Значение ключа получается только ты знаешь и оно в .env файле, который в репозиторий не попадет 

Про работу спросил, потому что другие энв переменные через ENV достаются

2025-11-13 16:22 UTC, VVOvsyannikov commented
Решил вернуться и доделать проект спустя 3 года :)
Допилил конфиги роллбара и ньюрелика, заново задеплоил с помощью Kamal на свой ВПС. 
Метрики в Newrelic работают, ошибки в Rollbar улетают.

2025-11-17 09:23 UTC, YJorge approved these changes

2025-11-17 14:33 UTC, merged